name: photo_manager_example
description: Demonstrates how to use the photo_manager plugin.
version: 2.5.2+25
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  oktoast: ^3.4.0
  path_provider: ^2.1.1
  photo_manager:
    path: ../
  provider: ^6.0.5
  url_launcher: ^6.2.1
  video_player: ^2.8.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
